### ISSUE TITLE
Why does the view controller need to conform to `AVAudioPlayerDelegate`?

### ISSUE THREAD

**Issue by mapostolakis** [chrzarma/Xylophone#3]
https://github.com/chrzarma/Xylophone/blob/3e62b4d6f04d13ae302757572c72963bd744f715/Xylophone/%20VIewController.swift#L12

**Comment by chrzarma** [comment]
So that we can add sounds in our app

**Comment by mapostolakis** [comment]
Remove the protocol conformance and try to run the app. Do you notice any differences?

**Comment by chrzarma** [comment]
No differences at all.Because we don 't use any audioplayer delegate in our code to handle anything.

**Comment by mapostolakis** [comment]
👍🏼
